package edu.demart_api.controller;

import edu.demart_api.dto.request.*;
import edu.demart_api.dto.response.ApiResponse;
import edu.demart_api.dto.response.AuthResponse;
import edu.demart_api.dto.response.StaffApplicationResponse;
import edu.demart_api.service.AuthService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/v1")
public class AuthController {

    private final AuthService authService;

    public AuthController(AuthService authService) {
        this.authService = authService;
    }

    // ─── Public Endpoints ────────────────────────────────────────────────────

    /** Request email verification OTP code at time of registration */
    @PostMapping("/auth/register/send-otp")
    public ResponseEntity<ApiResponse<String>> sendRegistrationOtp(
            @Valid @RequestBody SendRegistrationOtpRequest request) {
        String otp = authService.sendRegistrationOtp(request);
        return ResponseEntity.ok(ApiResponse.success("Registration OTP sent to email. Code: " + otp, otp));
    }

    /** Verify registration OTP code & complete account creation */
    @PostMapping("/auth/register/verify-otp")
    public ResponseEntity<ApiResponse<AuthResponse>> verifyRegistrationOtp(
            @Valid @RequestBody VerifyRegistrationOtpRequest request) {
        AuthResponse authResponse = authService.verifyRegistrationOtp(request);
        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(ApiResponse.success("Registration successful! Welcome to Mini D-Mart.", authResponse));
    }

    /** Public self-apply to register as Staff / Restaurant Partner (Password will be generated by Admin) */
    @PostMapping("/auth/staff-request")
    public ResponseEntity<ApiResponse<StaffApplicationResponse>> applyForStaff(
            @Valid @RequestBody StaffApplicationRequest request) {
        StaffApplicationResponse response = authService.applyForStaff(request);
        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(ApiResponse.success("Staff application submitted! Admin will generate your password and notify you via email.", response));
    }

    /** Direct customer registration fallback */
    @PostMapping("/auth/register")
    public ResponseEntity<ApiResponse<AuthResponse>> register(
            @Valid @RequestBody RegisterRequest request) {
        AuthResponse authResponse = authService.register(request);
        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(ApiResponse.success("Registration successful", authResponse));
    }

    @PostMapping("/auth/login")
    public ResponseEntity<ApiResponse<AuthResponse>> login(
            @Valid @RequestBody LoginRequest request) {
        AuthResponse authResponse = authService.login(request);
        return ResponseEntity.ok(ApiResponse.success("Login successful", authResponse));
    }

    /** Request password reset OTP code */
    @PostMapping("/auth/forgot-password")
    public ResponseEntity<ApiResponse<String>> forgotPassword(
            @Valid @RequestBody ForgotPasswordRequest request) {
        String otp = authService.forgotPassword(request);
        return ResponseEntity.ok(ApiResponse.success("Reset code generated: " + otp, otp));
    }

    /** Reset password using OTP code */
    @PostMapping("/auth/reset-password")
    public ResponseEntity<ApiResponse<Void>> resetPassword(
            @Valid @RequestBody ResetPasswordRequest request) {
        authService.resetPassword(request);
        return ResponseEntity.ok(ApiResponse.success("Password reset successfully. Please sign in with your new password.", null));
    }

    // ─── Admin-only Endpoints ────────────────────────────────────────────────

    /** Admin views staff & restaurant partner applications */
    @GetMapping("/admin/staff-requests")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<ApiResponse<List<StaffApplicationResponse>>> getStaffApplications(
            @RequestParam(required = false) String status) {
        List<StaffApplicationResponse> list = authService.getStaffApplications(status);
        return ResponseEntity.ok(ApiResponse.success("Staff applications fetched", list));
    }

    /** Admin approves application & generates/sets staff password */
    @PostMapping("/admin/staff-requests/{id}/approve")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<ApiResponse<AuthResponse>> approveStaffApplication(
            @PathVariable Long id,
            @RequestBody(required = false) ApproveStaffApplicationRequest request) {
        AuthResponse authResponse = authService.approveStaffApplication(id, request);
        return ResponseEntity.ok(ApiResponse.success("Staff account approved & credentials emailed to applicant!", authResponse));
    }

    /** Admin rejects staff application */
    @PostMapping("/admin/staff-requests/{id}/reject")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<ApiResponse<Void>> rejectStaffApplication(
            @PathVariable Long id,
            @RequestParam(defaultValue = "Application does not meet requirements") String reason) {
        authService.rejectStaffApplication(id, reason);
        return ResponseEntity.ok(ApiResponse.success("Staff application rejected", null));
    }

    /** Admin manually creates a STAFF or ADMIN account directly */
    @PostMapping("/admin/users")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<ApiResponse<AuthResponse>> createUser(
            @Valid @RequestBody RegisterRequest request,
            @RequestParam(defaultValue = "STAFF") String role) {
        AuthResponse authResponse = authService.createUserWithRole(request, role);
        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(ApiResponse.success("User created with role " + role.toUpperCase(), authResponse));
    }
}
