spring.application.name=dmart-api

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/D-mart
spring.datasource.username=postgres
spring.datasource.password=tiger

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081

# JPA open-in-view
spring.jpa.open-in-view=false
