spring.application.name=dmart-api

# PostgreSQL - reads from environment variables on Render, falls back to local values
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-cool-wind-ax5a7vqc-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_zHCcph8un4aZ}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Server
server.port=${PORT:8081}

# JPA open-in-view
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:86400000}
