spring.application.name=dmart-api

# Neon PostgreSQL Dat abase
spring.datasource.url=jdbc:postgresql://ep-cool-wind-ax5a7vqc-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zHCcph8un4aZ

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8081

# JPA open-in-view
spring.jpa.open-in-view=false
